[package]
name = "srv-control-ingest"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
fs2.workspace = true
rusqlite.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
srv-common = { path = "../../crates/srv-common" }
